version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: ts-service-dev
    container_name: ts-service-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./src:/usr/src/app/src
