version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: ts-service
    container_name: ts-service
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
