version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: ts-service-dev
    container_name: ts-service-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./src:/usr/src/app/src
  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: ts-service-test
    container_name: ts-service-test
    restart: unless-stopped
    volumes:
      - ./src:/usr/src/app/src
      - ./test:/usr/src/app/test